# Generated by Django 5.1 on 2024-09-26 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_resposta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='acervovideos',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.setores'),
        ),
    ]
