# Generated by Django 5.1 on 2024-09-26 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_acervovideos_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_modulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='acervovideos',
            name='treinamento',
        ),
        migrations.AddField(
            model_name='acervovideos',
            name='modulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modulos'),
        ),
    ]
