# Generated by Django 4.2.15 on 2024-09-27 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.modulos'),
        ),
    ]
