# Generated by Django 5.1 on 2024-09-27 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_material_modulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acervovideos',
            name='modulo',
        ),
    ]
