# Generated by Django 5.1 on 2024-09-28 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_acervovideos_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulos',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.acervovideos'),
        ),
    ]
