# Generated by Django 4.2.15 on 2024-09-29 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_modulos_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255)),
                ('alternativa_a', models.CharField(max_length=255)),
                ('alternativa_b', models.CharField(max_length=255)),
                ('alternativa_c', models.CharField(max_length=255)),
                ('alternativa_d', models.CharField(max_length=255)),
                ('alternativa_e', models.CharField(blank=True, max_length=255, null=True)),
                ('resposta_correta', models.CharField(max_length=1)),
                ('modulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modulos')),
                ('treinamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.treinamentos')),
            ],
        ),
    ]
